import {
  WebsiteSettings,
  HeroSectionConfig,
  ThemeTemplateItem,
  ImageItem,
  GalleryPhoto,
  MusicTrack,
  ReviewItem,
  WishRecord,
  AnalyticsStats,
} from "../types/cms";

export const defaultHeroBgImage = new URL(
  "../assets/images/hero_birthday_banner_1785620810738.jpg",
  import.meta.url
).href;

export const defaultSettings: WebsiteSettings = {
  siteName: "CelebrationCraft Studio",
  logoUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=200&auto=format&fit=crop",
  faviconUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=64&auto=format&fit=crop",
  metaTitle: "CelebrationCraft Studio - Interactive Birthday & Wish Experiences",
  metaDescription: "Create beautiful interactive birthday websites with blowable candles, soundtrack music, surprise gifts, and magical confetti animations.",
  facebookUrl: "https://facebook.com/celebrationcraft",
  instagramUrl: "https://instagram.com/celebrationcraft",
  twitterUrl: "https://twitter.com/celebrationcraft",
  youtubeUrl: "https://youtube.com/celebrationcraft",
  tiktokUrl: "https://tiktok.com/@celebrationcraft",
  copyrightText: "© 2026 CelebrationCraft Studio. All rights reserved.",
  primaryColor: "#EE4374",
  accentColor: "#D82C5D",
  fontFamily: "Plus Jakarta Sans, Playfair Display, sans-serif",
  smtpHost: "smtp.mailtrap.io",
  smtpPort: "2525",
  smtpUser: "admin@celebrationcraft.com",
  smtpFrom: "no-reply@celebrationcraft.com",
  sectionHeadingFontSize: "text-3xl sm:text-5xl",
  bodyTextFontSize: "text-sm sm:text-base",
  galleryPhotoAspect: "aspect-square",
  galleryPhotoFit: "object-cover",
  galleryPhotoHeight: "h-48",
};

export const defaultHero: HeroSectionConfig = {
  headline: "Make Them\nFeel Truly Special",
  subheading: "Create stunning digital birthday pages and celebration websites for anniversaries, Valentine's, and every moment that deserves more than just a simple wish.",
  buttonText: "Create Your Wish →",
  buttonLink: "/creator",
  heroBgImage: defaultHeroBgImage,
  badgeText: "#1 Digital Celebration Platform | Voted Top Brand",
  ratingText: "4.9/5 Rating",
  wishesCreatedCount: "1.2M+",
  lovedByCount: "12K+",
  customerAvatars: [
    "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=100&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=100&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=100&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100&auto=format&fit=crop",
  ],
  showHeroSection: true,
  showBadge: true,
  showRating: true,
  showAvatars: true,
  headlineFontSize: "text-5xl sm:text-7xl lg:text-8xl",
  subheadingFontSize: "text-base sm:text-lg md:text-xl",
  badgeFontSize: "text-xs sm:text-sm",
  buttonFontSize: "text-base sm:text-lg",
  heroPhotoPlacement: "background",
  heroPhotoPosition: "object-[82%_center]",
  heroPhotoFit: "object-cover",
  heroPhotoSize: "w-full",
  heroPhotoHeight: "min-h-[580px] lg:min-h-[640px]",
  heroPhotoOpacity: 100,
};

export const defaultTemplates: ThemeTemplateItem[] = [
  {
    id: "interactive-suite",
    name: "Interactive Blowable Candle Suite",
    thumbnailUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=600&auto=format&fit=crop",
    category: "Interactive",
    description: "Features blowable candle simulation via microphone/click, 3D gift unboxing, and popping balloons.",
    priceType: "free",
    buttonText: "Use Template",
    buttonLink: "/creator?template=interactive-suite",
    tags: ["Candle", "Interactive", "Popular", "3D"],
    status: "published",
    orderIndex: 1,
  },
  {
    id: "royal-luxury",
    name: "Royal Luxury Gold Edition",
    thumbnailUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=600&auto=format&fit=crop",
    category: "Luxury",
    description: "Premium dark obsidian and gold aesthetics with velvet fireworks and orchestral audio soundtrack.",
    priceType: "premium",
    buttonText: "Use Template",
    buttonLink: "/creator?template=royal-luxury",
    tags: ["Gold", "Luxury", "VIP"],
    status: "published",
    orderIndex: 2,
  },
  {
    id: "sweet-pastel",
    name: "Sweet Pastel & Polaroid Memories",
    thumbnailUrl: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=600&auto=format&fit=crop",
    category: "Floral",
    description: "Soft pink pastel theme featuring vintage polaroid photo galleries, drifting hearts, and ambient music.",
    priceType: "free",
    buttonText: "Use Template",
    buttonLink: "/creator?template=sweet-pastel",
    tags: ["Pastel", "Memories", "Cute"],
    status: "published",
    orderIndex: 3,
  },
  {
    id: "cyberpunk-neon",
    name: "Cyberpunk Neon Party Suite",
    thumbnailUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop",
    category: "Cyberpunk",
    description: "Futuristic neon glowing laser canvas with retro synthwave beats and holographic typography.",
    priceType: "premium",
    buttonText: "Use Template",
    buttonLink: "/creator?template=cyberpunk-neon",
    tags: ["Neon", "Party", "Cyberpunk"],
    status: "published",
    orderIndex: 4,
  },
  {
    id: "glassmorphism-envelope",
    name: "Glassmorphism Envelope & Precious Memories",
    thumbnailUrl: "https://i.postimg.cc/T1WkQP0S/IMG-7302.avif",
    category: "Interactive",
    description: "Interactive envelope opening experience, typing effect, floating stars & balloons canvas, photo memory grid, funny squabbles section, and final surprise popup modal.",
    priceType: "free",
    buttonText: "Use Template",
    buttonLink: "/creator?template=glassmorphism-envelope",
    tags: ["Envelope", "Memories", "Interactive", "Glassmorphism"],
    status: "published",
    orderIndex: 5,
  },
];

export const defaultImages: ImageItem[] = [
  {
    id: "img-hero-banner",
    name: "Hero Birthday Celebration Banner",
    url: defaultHeroBgImage,
    folder: "Hero",
    fileSize: "1.2 MB",
    fileType: "JPG",
    uploadedAt: "2026-08-01",
  },
  {
    id: "img-gal-1",
    name: "Birthday Party Confetti Joy",
    url: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=600&auto=format&fit=crop",
    folder: "Gallery",
    fileSize: "850 KB",
    fileType: "JPG",
    uploadedAt: "2026-08-01",
  },
  {
    id: "img-gal-2",
    name: "Golden Sparkler Cake Celebration",
    url: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=600&auto=format&fit=crop",
    folder: "Gallery",
    fileSize: "920 KB",
    fileType: "JPG",
    uploadedAt: "2026-08-01",
  },
  {
    id: "img-gal-3",
    name: "Surprise Gift Box Unboxing",
    url: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=600&auto=format&fit=crop",
    folder: "Gallery",
    fileSize: "740 KB",
    fileType: "JPG",
    uploadedAt: "2026-08-01",
  },
];

export const defaultGallery: GalleryPhoto[] = [
  {
    id: "gal-1",
    title: "Candle Light Moment",
    imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?q=80&w=600&auto=format&fit=crop",
    caption: "Blowing out candles with realistic air sound effects",
    orderIndex: 1,
  },
  {
    id: "gal-2",
    title: "Surprise Unboxing",
    imageUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=600&auto=format&fit=crop",
    caption: "Interactive 3D gift boxes with hidden notes and photo popups",
    orderIndex: 2,
  },
  {
    id: "gal-3",
    title: "Balloon Popping Joy",
    imageUrl: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?q=80&w=600&auto=format&fit=crop",
    caption: "Pop floating metallic balloons with audio haptics and confetti",
    orderIndex: 3,
  },
];

export const defaultMusicTracks: MusicTrack[] = [
  {
    id: "track-happy-birthday-classic",
    title: "Happy Birthday Piano Melody",
    artist: "CelebrationCraft Studio",
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3",
    isDefault: true,
    autoplay: true,
    defaultVolume: 0.7,
  },
  {
    id: "track-[#EE4374]-orchestral",
    title: "Grand Celebration Symphony",
    artist: "CelebrationCraft Studio",
    audioUrl: "https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8ad3d0e.mp3",
    isDefault: false,
    autoplay: false,
    defaultVolume: 0.8,
  },
  {
    id: "track-lofi-birthday",
    title: "Warm Acoustic Birthday Chill",
    artist: "CelebrationCraft Studio",
    audioUrl: "https://cdn.pixabay.com/download/audio/2021/08/09/audio_a1622f99b1.mp3",
    isDefault: false,
    autoplay: false,
    defaultVolume: 0.6,
  },
];

export const defaultReviews: ReviewItem[] = [
  {
    id: "rev-1",
    customerName: "Sophia Martinez",
    customerImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=120&auto=format&fit=crop",
    rating: 5,
    reviewText: "My best friend cried tears of joy when she blew out the virtual candle on her phone! The blowable microphone feature is pure magic.",
    status: "approved",
    createdAt: "2026-07-28",
  },
  {
    id: "rev-2",
    customerName: "David Chen",
    customerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=120&auto=format&fit=crop",
    rating: 5,
    reviewText: "Created a surprise wish website for my daughter in 2 minutes. The polaroid photo memory gallery and gift box unboxing blew everyone away!",
    status: "approved",
    createdAt: "2026-07-29",
  },
  {
    id: "rev-3",
    customerName: "Emily Watson",
    customerImage: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=120&auto=format&fit=crop",
    rating: 5,
    reviewText: "The interactive balloons, background music, and instant shareable link make this 100x better than any physical birthday card.",
    status: "approved",
    createdAt: "2026-07-30",
  },
];

export const defaultWishes: WishRecord[] = [
  {
    id: "birthday-demo",
    recipientName: "Sarah",
    senderName: "Friends & Family",
    templateId: "interactive-suite",
    message: "May your birthday be filled with endless smiles, laughter, sweet surprises, and unforgettable moments!",
    viewsCount: 3420,
    createdAt: "2026-07-25",
    status: "active",
  },
  {
    id: "alex-wish",
    recipientName: "Alex",
    senderName: "Sarah",
    templateId: "royal-luxury",
    message: "Happy 30th Birthday Alex! Wishing you health, success, and pure happiness always.",
    viewsCount: 1280,
    createdAt: "2026-07-27",
    status: "active",
  },
  {
    id: "emma-sweet-16",
    recipientName: "Emma",
    senderName: "Mom & Dad",
    templateId: "sweet-pastel",
    message: "Happy Sweet 16 Emma! You bring so much light and love into our lives every single day.",
    viewsCount: 2150,
    createdAt: "2026-07-30",
    status: "active",
  },
];

export const defaultAnalytics: AnalyticsStats = {
  visitorsCount: 48920,
  pageViewsCount: 142850,
  templatesCreatedCount: 8940,
  totalWishesCount: 124500,
  downloadsCount: 3120,
};
